*** Requirements

    - [X] Theme paragraphs with CSS
    - [X] Theme header tags with CSS
    - [X] Theme images and images captions with CSS
    - [x] Change the colour scheme to something aesthetically pleasing
    - [X] Apply 1 CSS file to 3 gutenberg documents.
    - [X] Include all 3 gutenberg documents HTML and assets, with the CSS applied.
    - [X] document in your README what modifications you had to make
      to the project gutenberg HTML files.
    - [X] Take 3 screenshots of firefox running all of your pages that
      demonstrates your theme.

** Part II

   You're going to make your own HTML page and you're going to make 2
   CSS themes for it.

   Emulate the 2nd and 3rd design from this comic:
   http://theoatmeal.com/comics/design_hell

   But instead make a 1 webpage about each assignment partner (1 page
   if you are doing this solo and 2 webpages that advertises you to
   employers.

   Include at least 3 sections:

   Who you are + photo

   Your professional history

   What you can do for a potential employer/what you have to offer

   Then a sidebar of important points they should know about you.

   Make 1 ugly CSS and 1 good CSS just like the design_hell comic.

   You should make a page good enough you'd actually use it as your homepage.

*** Requirements

    - [ ] 4 sections: who you are, your history, what you have to
      offer, important points about you
    - [ ] 1 Ugly CSS theme
    - [ ] 1 good CSS theme
    - [ ] Ugly theme has to be noticeabley different.
    - [ ] 2 HTML files, each with the same content but different CSS
    - [ ] your photo (try to keep it professional)
    - [ ] Take 2 screenshots of firefox running all of your pages that
      demonstrates your theme.
    - [ ] Ensure that files are appropriately named and CASE SENSITIVE.

    - [X] homepage/good.html should host your good page
    - [X] homepage/ugly.html should host your ugly page
    - [X] gutenberg/1.html should host your first gutenberg book
    - [X] gutenberg/2.html should host your second gutenberg book
    - [X] gutenberg/3.html should host your third gutenberg book
    - [ ] screenshots good.png, bad.png, gutenberg1.png, gutenberg2.png, gutenberg3.png should be in the root of the project.


** Marking.
   - 3 marks for the 2 versions of your page. Including HTML files.
   - 1 mark for making the CSS for your promotion pages look as close
     to theoatmeal comic as possible (don't steal his images).

   Marks will be deducted for lack of screenshots and lack of README or wrong file locations.
